.TH "asm/asm.h" 3 "Fri Jun 30 2017" "Project_C_Elec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
asm/asm.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBparseAsm\fP (FILE *fin)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void parseAsm (FILE * fin)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Project_C_Elec from the source code\&.
