.TH "_etapeNode" 3 "Fri Jun 30 2017" "Project_C_Elec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_etapeNode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "int \fBactive\fP"
.br
.ti -1c
.RI "struct \fB_actionNode\fP * \fBactions\fP"
.br
.ti -1c
.RI "struct \fB_transitionRefNode\fP * \fBtransitionsAmont\fP"
.br
.ti -1c
.RI "int \fBnbTransitionsAmont\fP"
.br
.ti -1c
.RI "struct \fB_transitionRefNode\fP * \fBtransitionsAval\fP"
.br
.ti -1c
.RI "int \fBnbTransitionsAval\fP"
.br
.ti -1c
.RI "struct \fB_etapeNode\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fB_actionNode\fP* actions"

.SS "int active"

.SS "int id"

.SS "char* name"

.SS "int nbTransitionsAmont"

.SS "int nbTransitionsAval"

.SS "struct \fB_etapeNode\fP* next"

.SS "struct \fB_transitionRefNode\fP* transitionsAmont"

.SS "struct \fB_transitionRefNode\fP* transitionsAval"


.SH "Author"
.PP 
Generated automatically by Doxygen for Project_C_Elec from the source code\&.
