.TH "_transitionNode" 3 "Fri Jun 30 2017" "Project_C_Elec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_transitionNode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "struct \fB_etapeRefNode\fP * \fBetapesAmont\fP"
.br
.ti -1c
.RI "int \fBnbEtapesAmont\fP"
.br
.ti -1c
.RI "struct \fB_etapeRefNode\fP * \fBetapesAval\fP"
.br
.ti -1c
.RI "int \fBnbEtapesAval\fP"
.br
.ti -1c
.RI "\fBnodeType\fP * \fBreceptivite\fP"
.br
.ti -1c
.RI "struct \fB_transitionNode\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fB_etapeRefNode\fP* etapesAmont"

.SS "struct \fB_etapeRefNode\fP* etapesAval"

.SS "int id"

.SS "char* name"

.SS "int nbEtapesAmont"

.SS "int nbEtapesAval"

.SS "struct \fB_transitionNode\fP* next"

.SS "\fBnodeType\fP* receptivite"


.SH "Author"
.PP 
Generated automatically by Doxygen for Project_C_Elec from the source code\&.
