.TH "operatorNodeType" 3 "Fri Jun 30 2017" "Project_C_Elec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
operatorNodeType
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBoper\fP"
.br
.ti -1c
.RI "int \fBnOperands\fP"
.br
.ti -1c
.RI "struct \fBnodeTypeTag\fP ** \fBop\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int nOperands"

.SS "struct \fBnodeTypeTag\fP** op"

.SS "int oper"


.SH "Author"
.PP 
Generated automatically by Doxygen for Project_C_Elec from the source code\&.
