.TH "_actionNode" 3 "Fri Jun 30 2017" "Project_C_Elec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_actionNode
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBname\fP"
.br
.ti -1c
.RI "\fBnodeType\fP * \fBexpr\fP"
.br
.ti -1c
.RI "struct \fB_actionNode\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBnodeType\fP* expr"

.SS "char* name"

.SS "struct \fB_actionNode\fP* next"


.SH "Author"
.PP 
Generated automatically by Doxygen for Project_C_Elec from the source code\&.
