.TH "identifierNodeType" 3 "Fri Jun 30 2017" "Project_C_Elec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
identifierNodeType
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ast\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBident\fP"
.br
.ti -1c
.RI "int \fBkey\fP"
.br
.ti -1c
.RI "int \fBflag\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int flag"

.SS "char* ident"

.SS "int key"


.SH "Author"
.PP 
Generated automatically by Doxygen for Project_C_Elec from the source code\&.
