.TH "asm/asm.c" 3 "Fri Jun 30 2017" "Project_C_Elec" \" -*- nroff -*-
.ad l
.nh
.SH NAME
asm/asm.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include 'vm_codops\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBparseAsm\fP (FILE *fin)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.SS "void parseAsm (FILE * fin)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Project_C_Elec from the source code\&.
